package com.mercadopago.android.px.addons;

import android.support.annotation.NonNull;
import com.mercadopago.android.px.addons.model.Track;
import java.util.Map;

/**
 * Implement this interface to manage PX view and event's tracks.
 */
public interface TrackingBehaviour {

    /**
     * @deprecated use application context in class {@link com.mercadopago.android.px.addons.model.Track}
     */
    @Deprecated
    default void setApplicationContext(@NonNull final String applicationContext) { }

    /**
     * This method is called when a new view is shown to the user.
     *
     * @param path is the Checkout's path to the view being shown. Paths start with prefixes
     * @param data Map containing information that the view is showing. It also contains information about errors if the
     * view launched is the Error view. Keys are dynamically generated by mapping models under the package
     *
     * @deprecated use {@link #track(Track)} instead
     */
    @Deprecated
    default void onView(@NonNull final String path, @NonNull final Map<String, ?> data) { }

    /**
     * This method is called when a new event is launched by the user.
     *
     * @param path is the Checkout's path to the event being performed by the user. Event paths' start with prefixes
     * that are described in
     * @param data Map containing information about the event performed. Keys are dynamically generated by mapping
     * models under the package
     *
     * @deprecated use {@link #track(Track)} instead
     */
    @Deprecated
    default void onEvent(@NonNull final String path, @NonNull final Map<String, ?> data) { }

    /**
     * This method is called when a new track is meant to be tracked
     *
     * @param track with the data to track
     */
    default void track(@NonNull final Track track) { }
}